version: '3.1'
services:

  proxy:
    build: ./proxy/
    ports:
      - '9000:80'
    restart: always

  frontend_prod:
    build: ./frontend/nginx/
    ports:
      - '3000'
    depends_on:
      - api_prod
    restart: always

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 840917

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080'

  api_prod:
    build: ./backend/api/
    command: npm run production
    ports:
      - '3333'
    depends_on:
      - db