version: '3.1'
services:

  proxy:
    build: ./proxy/
    ports:
      - '9000:80'
    restart: always
    depends_on:
      - frontend_prod
      - api_prod
      - pg_admin

  frontend_prod:
    build: ./frontend/nginx/
    ports:
      - '3000'
    depends_on:
      - api_prod
    restart: always

  
  api_prod:
    build: ./backend/api/
    command: npm run production
    ports:
      - '3333'
    depends_on:
      - postgres

  pg_admin:
    image: 'dpage/pgadmin4'
    ports:
      - '5050:5050'
    environment:
      PG_ADMIN_DEFAULT_EMAIL: sebbe@sebbe.dev
      PG_ADMIN_DEFAULT_PASSWORD: asdf123

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: asdf123
