version: '3.1'
services:

  proxy:
    build: ./proxy/
    ports:
      - '9000:80'
    restart: always
    depends_on:
      - frontend_prod
      - api_prod

  frontend_prod:
    build: ./frontend/nginx/
    ports:
      - '3000'
    depends_on:
      - api_prod
    restart: always

  
  api_prod:
    build: ./backend/api/
    command: npm run production
    ports:
      - '3333'
    depends_on:
      - db

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_USER: sebbe
      MYSQL_PASSWORD: asdf123
      MYSQL_DATABASE: studentprojekt
      MYSQL_ROOT_PASSWORD: asdf123
    ports:
      - '3306:3306'
