version: '3.1'
services:

  proxy:
    build: ./proxy/
    ports:
      - '9000:80'
    restart: always
    depends_on:
      - frontend
      - api

  frontend:
    build: ./frontend/nginx/
    ports:
      - '3000'
    depends_on:
      - api
    restart: always

  
  api:
    build: ./backend/api/
    command: npm run production
    ports:
      - '3333'
    depends_on:
      - db
    environment:
      HOST: ${HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DB: ${DB_DB}
      EMAIL: ${EMAIL}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}

  db:
    build: ./backend/api/database/
    restart: always
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DB}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
