version: '3.1'
services:

  proxy:
    build: ./proxy/
    ports:
      - '9000:80'
    restart: always
    depends_on:
      - frontend
      - api_prod

  frontend:
    build: ./frontend/nginx/
    ports:
      - '3000'
    depends_on:
      - api_prod
    restart: always

  
  api:
    build: ./backend/api/
    command: npm run production
    ports:
      - '3333'
    depends_on:
      - db
    environment:
      HOST: 'https://sebbe.dev/studentprojekt'

  db:
    build: ./backend/api/database/
    restart: always
    environment:
      MYSQL_USER: sebbe
      MYSQL_PASSWORD: asdf123
      MYSQL_DATABASE: studentprojekt
      MYSQL_ROOT_PASSWORD: asdf123
    ports:
      - '3306:3306'
