version: '3.1'
services:

  frontend:
    build: ./frontend/
    command: npm run start
    volumes:
      - ./frontend/:/usr/app/
      - /frontend/node_modules/
    ports:
      - '3000:3000'

  db:
    build: ./backend/api/database/
    restart: always
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DB}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - '3306:3306'
      
  api:
    build: ./backend/api/
    command: npm run dev
    volumes:
      - ./backend/api/:/usr/app/
      - /backend/api/node_modules
    ports:
      - '3333:3333'
    depends_on:
      - db
    environment:
      HOST: ${HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DB: ${DB_DB}
      EMAIL: ${EMAIL}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}